defaultSemverRangePrefix: ""

nodeLinker: node-modules

npmRegistries:
  //registry.npmjs.org:
    npmAuthToken: "${NPM_AUTH_TOKEN:-''}"

preferInteractive: true

yarnPath: .yarn/releases/yarn-4.2.2.cjs
