name: Publish

on:
  release:
    types:
      - published

permissions: read-all

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          check-latest: true
          registry-url: https://registry.npmjs.org

      - run: corepack enable

      - run: pnpm install --frozen-lockfile

      - run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
